export { default as Login } from './Login/Login.jsx'
export { default as Landing } from './Landing/Landing.jsx'
export { default as Register } from './Register/Register.jsx'
export { default as Services } from './Services/Services.jsx'
export { default as Profile } from './Profile/Profile.jsx'